config/routes.rb
Rails.application.routes.draw do
  get 'favorites'=>'favorites#index', as: :favorites
  get 'favorites/:album_id'=> 'favorites#create', as: :favorite_create
  delete 'favorites/:album_id'=> 'favorites#destroy', as: :favorite_destroy
  get 'explore' => 'explore#index' , as: :explore
  get 'explore/trends' => 'explore#trends' , as: :trends
  get 'search' => 'search#index' , as: :search
  post 'track' => 'track#create', as: :tracks
  delete 'track/:album_id/:track_id' => 'track#destroy', as: :track_destroy
  resources :albums do
  get '/myalbums/:page', action: :myalbums, on: :collection , as: :my
  get '/myalbums/', action: :myalbums, on: :collection 
  end
  devise_for :users
   root "home#index"
end

app/views/partials/navbar/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top text-white">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Disc<i class="fa-solid text-sec fa-compact-disc o-icon"></i>tic</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fa-solid fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <%= form_with(url: search_path,class: 'input-group w-50 m-auto', method: :get, data: {controller:'search', search_target:'form', turbo_frame: "results", turbo_action:'advance', action: 'input->search#submit_query'} ) do |form| %>
        <%= form.text_field :query, :authenticity_token => false, :class => "form-control",:placeholder => "Album,title,artist..." , :value => params[:query]%>
        <button class="btn btn-outline-warning dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Explore</button>
        <ul class="dropdown-menu dropdown-menu-end bg-sec">
          <li><%= link_to 'Explore All', explore_path ,class: "dropdown-item" %></li>
          <li><%= link_to 'Trendings', trends_path ,class: "dropdown-item" %></li>
        </ul>
      <% end %>
      <ul class="navbar-nav  mb-2 mb-lg-0">
        <% if user_signed_in?  %>
          <li class="nav-item dropdown">
            <button class="btn btn-warning dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fa-regular fa-circle-user"></i>
            </button>
            <ul class="dropdown-menu dropdown-menu-end bg-main text-white" aria-labelledby="navbarDropdownMenuLink">
              <li><a class="dropdown-item disabled" href="#"><%= current_user.email %> </a></li>
              <li><%= link_to raw('<i class="fa-brands fa-gratipay"></i> My Favorites'), favorites_path ,class: 'dropdown-item text-sec' %></li>
              <li><%= link_to raw('<i class="fa-solid fa-record-vinyl"></i> My Albums'), my_albums_url(1) ,class: 'dropdown-item text-sec' %></li>
              <li> <%= link_to raw('<i class="fa-solid fa-arrow-right-from-bracket"></i> Logout'), destroy_user_session_path,  data: {turbo_method: :delete} ,class: 'dropdown-item text-danger' %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", new_session_path(User), class:"btn btn-warning bg-sec" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>