config/routes.rb
Rails.application.routes.draw do
  get 'favorites'=>'favorites#index', as: :favorites
  get 'favorites/:album_id'=> 'favorites#create', as: :favorite_create
  delete 'favorites/:album_id'=> 'favorites#destroy', as: :favorite_destroy
  get 'explore' => 'explore#index' , as: :explore
  get 'explore/trends' => 'explore#trends' , as: :trends
  get 'search' => 'search#index' , as: :search
  post 'track' => 'track#create', as: :tracks
  delete 'track/:album_id/:track_id' => 'track#destroy', as: :track_destroy
  resources :albums do
  get '/myalbums/:page', action: :myalbums, on: :collection , as: :my
  get '/myalbums/', action: :myalbums, on: :collection 
  end
  devise_for :users
   root "home#index"
end

app/models/album.rb
class Album < ApplicationRecord
  # associations
  belongs_to :user, counter_cache: true
  has_many :tracks, dependent: :delete_all
  has_many :favorites, dependent: :delete_all

  # validations
  validates :name, presence: true, length: { maximum: 50 }
  validates :artist, presence: true, length: { maximum: 50 }
  validates :genre, presence: true, length: { maximum: 50 }
  validates :style, presence: true, length: { maximum: 50 }
  validates :format, presence: true, length: { maximum: 50 }
  validates :release_date, presence: true
  validates :description, presence: true
  validates :image_data, presence: true

  # scopes
  scope :filter_by_genre, ->(genre) { where(genre:) }
  scope :filter_by_style, ->(style) { where(style:) }
  scope :filter_by_format, ->(format) { where(format:) }
  scope :filter_by_year, ->(year) { where('extract(year from release_date) = ?', year) }

  include ImageUploader::Attachment(:image)

  def self.search_albums(params)
    if params[:query].blank?
      []
    else
      where(
        'lower(name) LIKE :query OR lower(description) LIKE :query', query: "%#{params[:query].downcase}%"
      )
    end
  end

  def self.search_artists(params)
    if params[:query].blank?
      []
    else
      where(
        'lower(artist) LIKE :query', query: "%#{params[:query].downcase}%"
      )
    end
  end

  def self.generate_filters
    {
      all: all.count,
      genre: group(:genre).count,
      format: group(:format).count,
      style: group(:style).count,
      year: group("TO_CHAR(release_date, 'YYYY')").count
    }
  end

  def self.trends
    @trends = []
    generate_trends.each do |single|
      @trends << { score: ((single[0] / 2) + single[1]), name: single[2], id: single[3],
                   image: ActiveSupport::JSON.decode(single[4]) }
    end
    @trends
  end

  def self.trends_pos(id)
    @rank = 0
    generate_trends.each_with_index do |single, index|
      @rank = index + 1 if single[3] == id
    end
    @rank
  end

  def self.generate_trends
    pluck(:views, :searches, :name, :id, :image_data).sort_by do |views, searches|
      (views / 2) + searches
    end.reverse.first(6)
  end

  def self.recently_added
    order('created_at DESC').limit(6)
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:show]

  def new
    @album = Album.new
  end

  def edit
    @album = current_user.albums.find_by_id(params[:id])
    if @album.nil?
      redirect_to my_albums_url(1), error: 'Album not found, or not enough permissions'
    else
      render :edit
    end
  end

  def show
    @album = Album.find_by_id(params[:id])
    @track = Track.new
    @track_list = @album.tracks.order(created_at: :desc)
    if @album.nil?
      redirect_to my_albums_url(1), error: 'Album not found'
    else
      @rank = Album.trends_pos(@album.id)
      @favorite = current_user.favorites.where(album_id: @album.id).exists? if user_signed_in?
      @album.increment!(:searches) if params[:search]
      @album.increment!(:views)
      render :show
    end
  end

  def create
    @album = Album.new(album_params)
    @album.user_id = current_user.id
    if @album.save
      redirect_to my_albums_url(1), success: "#{@album.name} Album Created !"
    else
      redirect_to new_album_path, error: @album.errors.full_messages
    end
  end

  def myalbums
    @albums = current_user.albums.order(created_at: :desc).paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @album = current_user.albums.find(params[:id])
    if @album.destroy
      redirect_to my_albums_url(1), success: 'Album deleted'
    else
      redirect_to my_albums_url(1), error: "Couldn't delete album"
    end
  end

  def update
    @album = current_user.albums.find(params[:id])
    if @album.update(album_params)
      redirect_to my_albums_url(1), success: 'Album updated'
    else
      redirect_to my_albums_url(1), error: "Couldn't update album"
    end
  end

  private

  def album_params
    params.require(:album).permit(:name, :description, :artist, :release_date, :image, :genre, :style, :format)
  end
end

app/views/albums/edit.html.erb
<div class="container" data-controller="album">
  <div class="py-5 text-center">
    <h2>Update Album # <%= @album.id %> </h2>
  </div>
  <% if error %>
  <% error.each do |msg| %>
    <div class="alert alert-danger" role="alert">
      <%= msg %>
    </div>
  <% end %>
  <% end %>
  <div class="row">
    <div class="col-md-12 order-md-1">
      <%= form_for(@album,:html => {"data-turbo" => "false"}) do |f| %>
        <div class="row">
          <div class="col-md-6 mb-3">
            <%= f.label :name,"Album Name",for:"AlbumName" %>
            <%= f.text_field :name,required:true, class:"form-control",id:"AlbumName" %>
          </div>
          <div class="col-md-6 mb-3">
            <%= f.label :artist,"Artist Name",for:"artistName" %>
            <%= f.text_field :artist,required:true, class:"form-control",id:"artistName"%>
          </div>
        </div>
        <%= f.label :description,"Description",for:"Description" %>
        <%= f.text_area :description,required:true,class:"form-control mb-3",id:"Description",style:"height: 100px" %>
           <div class="row">
          <div class="col-md-6 mb-3">
            <%= f.label :release_date,"Release Date",for:"ReleaseDate" %>
            <%= f.date_field :release_date,required:true, class:"form-control",id:"ReleaseDate" %>
          </div>
          <div class="col-md-6 mb-3">
            <%= f.label :style,"Style",for:"Style" %>
            <%= f.text_field :style,required:true, class:"form-control",id:"Style" %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 mb-3">
            <%= f.label :genre ,"Genre",for:"Genre" %>
            <%= f.text_field :genre,required:true, class:"form-control",id:"Genre" %>
          </div>
          <div class="col-md-6 mb-3">
            <%= f.label :format,"Format",for:"Format" %>
            <%= f.text_field :format,required:true, class:"form-control",id:"Format" %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 mb-3">
            <%= f.file_field :image,required:true, class:"form-control",id:"ImageLink" %>
          </div>
        </div>
        <%= f.submit "Update",class:"w-100 btn btn-lg btn-warning mb-5" %>
      <% end %>
              <%= link_to "Cancel", my_albums_url(1) ,class:"w-40 btn btn-sm btn-danger mb-5" %>

    </div>
  </div>
</div>

app/views/albums/myalbums.html.erb
<div class="container py-4" data-controller="album">
  <% if success %>
    <div class="alert alert-success m-3" role="alert">
      <%= success %>
    </div>
  <% end %>
  <% if error %>
    <div class="alert alert-danger m-3" role="alert">
      <%= error %>
    </div>
  <% end %>
 <%= link_to raw('<i class="fa-solid fa-plus"></i> Add New Album'),new_album_path,class:"btn bg-main text-white mt-5 mb-2"  %>

  <div class="table-responsive">
    <table class="table table-striped text-start">
      <thead>
        <tr class="bg-main text-sec">
          <th scope="col-2">Album</th>
          <th scope="col-10">Description</th>
          <th scope="col-10">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @albums.each do |album|   %>
          <tr class="text-start">
            <td class="col-2">
              <div class="d-flex gap-1 flex-column justify-content-start align-items-start">
                <%= image_tag (album.image_url if album.image),alt: "Example Musics image" ,width:"100px",height:"100px"%>
                <b class=" m-0 bold mt-2"><%= album.name %></b>
                <p class="m-0"><%= album.artist %></p>
                <b class="m-0"><%= album.tracks_count %> Tracks </b>
              </div>
            </td>
            <td class=" col-10"><%= album.description %></td>
            <td>
              <div class="btn-group-vertical">
                 <%= link_to "Edit",edit_album_path(album.id) ,class:"btn btn-warning"  %>
                 <%= link_to "View",album_path(album.id) ,class:"btn bg-main text-white"  %>
                <%= link_to "Delete",album_path(album.id) ,data: {turbo_method: :delete, turbo_confirm: "#{ album.name } will be deleted ! Are you sure?"} ,class:"btn btn-danger"  %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="pagination">
    <%= will_paginate @albums , renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
</div>

app/views/albums/new.html.erb
<div class="container" data-controller="album">
  <div class="py-5 text-center">
    <h2>Add New Album</h2>
  </div>
  <% if error %>
    <% error.each do |msg| %>
      <div class="alert alert-danger" role="alert">
        <%= msg %>
      </div>
    <% end %>
  <% end %>
  <div class="row">
    <div class="col-md-12 order-md-1">
      <%= form_for(@album,:html => {"data-turbo" => "false"}) do |f| %>
        <div class="row">
          <div class="col-md-6 mb-3">
            <%= f.label :name,"Album Name",for:"AlbumName" %>
            <%= f.text_field :name,required:true, class:"form-control",id:"AlbumName" %>
          </div>
          <div class="col-md-6 mb-3">
            <%= f.label :artist,"Artist Name",for:"artistName" %>
            <%= f.text_field :artist,required:true, class:"form-control",id:"artistName"%>
          </div>
        </div>
        <%= f.label :description,"Description",for:"Description" %>
        <%= f.text_area :description,required:true,class:"form-control mb-3",id:"Description",style:"height: 100px" %>
        <div class="row">
          <div class="col-md-6 mb-3">
            <%= f.label :release_date,"Release Date",for:"ReleaseDate" %>
            <%= f.date_field :release_date,required:true, class:"form-control",id:"ReleaseDate" %>
          </div>
          <div class="col-md-6 mb-3">
            <%= f.label :style,"Style",for:"Style" %>
            <%= f.text_field :style,required:true, class:"form-control",id:"Style" %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 mb-3">
            <%= f.label :genre ,"Genre",for:"Genre" %>
            <%= f.text_field :genre,required:true, class:"form-control",id:"Genre" %>
          </div>
          <div class="col-md-6 mb-3">
            <%= f.label :format,"Format",for:"Format" %>
            <%= f.text_field :format,required:true, class:"form-control",id:"Format" %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 mb-3">
            <%= f.file_field :image,required:true, class:"form-control",id:"ImageLink" %>
          </div>
        </div>
        <%= f.submit "Create Album",class:"w-100 btn btn-lg btn-warning mb-5" %>
      <% end %>
    </div>
  </div>
</div>

app/views/albums/show.html.erb
<div class="container py-5">
  <div class="row gutters-sm">
    <div class="col-md-4 mb-3">
      <div class="card  border-0 rounded" style='background:url("<%= (@album.image_url if @album.image) %>");'>
        <div class="card-body album_cover rounded" >
          <div class="d-flex flex-column align-items-center text-center">
            <%= image_tag (@album.image_url if @album.image),alt: "Example Musics image" ,width:"200px",height:"200px"%>
            <div class="mt-3">
              <h4 class="text-white"><%= @album.name %></h4>
              <p class="text-white mb-1">By <%= @album.artist %></p>
              <% if !@favorite %>
                <%= link_to  favorite_create_path(@album.id) , data: { turbo_method: "get" } do %>
                  <button class="btn bg-main text-white"><i class="fa-solid fa-star text-sec"></i> Add to Favorites</button>
                <% end %>
              <% else %>
                <%= link_to  favorite_destroy_path(@album.id) , data: { turbo_method: "delete" } do %>
                  <button class="btn bg-main text-white"><i class="fa-solid fa-circle-minus text-danger"></i> Remove From Favorites</button>
                <% end %>
              <% end %>
              <% if user_signed_in?  %>
                <% if current_user.id === @album.user_id %>
                  <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                    <i class="fa-solid fa-circle-plus"></i> Add Track
                  </button>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="card mt-3 bg-main text-sec">
        <ul class="list-group bg-main text-sec">
          <li class="list-group-item bg-main text-sec d-flex justify-content-between align-items-center flex-wrap">
            <h6 class="mb-0"><i class="fa-solid fa-user mx-2"></i>Added By</h6>
            <span class="text-white"><%= @album.user.email %></span>
          </li>
          <li class="list-group-item bg-main text-sec d-flex justify-content-between align-items-center flex-wrap">
            <h6 class="mb-0"><i class="fa-solid fa-calendar-days mx-2"></i>Release Date</h6>
            <span class="text-white"><%= @album.release_date.month %>/<%= @album.release_date.year %></span>
          </li>
          <li class="list-group-item bg-main text-sec d-flex justify-content-between align-items-center flex-wrap">
            <h6 class="mb-0"><i class="fa-solid fa-ranking-star mx-2"></i>Trendings</h6>
            <span class="text-white">
              <%if @rank > 0 %>
                #<%= @rank %>
              <% else %>
                Not Trending
              <% end %>
            </span>
          </li>
          <li class="list-group-item bg-main text-sec d-flex justify-content-between align-items-center flex-wrap">
            <h6 class="mb-0"><i class="fa-solid fa-chart-simple mx-2"></i>Views</h6>
            <span class="text-white"><%= @album.views %></span>
          </li>
          <li class="list-group-item bg-main text-sec d-flex justify-content-between align-items-center flex-wrap">
            <h6 class="mb-0"><i class="fa-solid fa-star mx-2"></i>Favorites</h6>
            <span class="text-white"><%= @album.favorites_count %></span>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-md-8">
      <b> Description: </b>
      <p class="fs-6 text-muted text-small">  <%= @album.description %> </p>
      <b> Playlist: </b>
      <div class="card mb-3 ">
        <div class="card-body p-0 ">
          <ul class="list-group bg-main music_list">
            <% if @track_list.empty? %>
              <li class="list-group-item bg-main text-white d-flex justify-content-center text-center align-items-center flex-wrap">
                <h6 class="mb-0"> No Tracks Found </h6>
              </li>
            <% end %>
            <% @track_list.each do |track| %>
              <li class="list-group-item bg-main text-white d-flex justify-content-between text-center align-items-center flex-wrap">
                <h6 class="mb-0"><i class="fa-solid fa-music mr-2"></i> <%= track.name %> <kbd class="ml-2 bg-sec text-dark"><%= track.time %>min</kbd> </h6>
                <div class="d-flex justify-content-center text-center align-items-center gap-2">
                  <span class="text-white"><a href=<%= track.spotify_link %> target="_blank" class="btn btn-sm btn-success d-flex justify-content-arround align-items-center "><i class="fa-brands fa-spotify mx-2 fa-lg"></i>Listen On Spotify</a></span>
                  <% if user_signed_in?  %>
                    <% if current_user.id === @album.user_id %>
                      <%= link_to raw("<i class='fa-solid fa-trash'></i>"),track_destroy_path(@album.id,track.id) ,data: {turbo_method: :delete, turbo_confirm: "#{ track.name } will be deleted ! Are you sure?"} ,class:"btn btn-danger btn-sm"  %>
                    <% end %>
                  <% end %>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<% if user_signed_in?  %>
  <% if current_user.id === @album.user_id %>
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog bg-main rounded border-0">
        <div class="modal-content bg-main text-center rounded text-sec border-0">
          <div class="modal-body border-0">
            <%= form_for(@track,:html => {"data-turbo" => "false"}) do |f| %>
              <div class="row">
                <div class="mb-3">
                  <%= f.label :name,"Track Name",for:"TrackName",class:"form-label" %>
                  <%= f.text_field :name,required:true, class:"form-control",id:"TrackName",placeholder:"Track Name" %>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6 mb-3">
                  <%= f.label :time,"Track Length(min)",for:"TrackLength",class:"form-label" %>
                  <%= f.number_field :time,required:true, class:"form-control",id:"TrackLength",placeholder:"Track Length" %>
                </div>
                <div class="col-md-6 mb-3">
                  <%= f.label :spotify_link,"Spotify Link",for:"TrackLink",class:"form-label" %>
                  <%= hidden_field_tag :album_id, "#{@album.id}" %>
                  <%= f.text_field :spotify_link,required:true, class:"form-control",id:"TrackLink",placeholder:"Paste your link..." %>
                </div>
              </div>
              <div class="modal-footer border-0">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <%= f.submit "Add to Album",class:"btn btn-warning" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>